name: Publish release package to the Maven Central Repository
on:
  release:
    types: [ created ]

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        version: [ a, b, c ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: build package
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} mvn -Pnative-jpackage clean package jpackage:jpackage

      - uses: actions/upload-artifact@v4
        with:
          name: log-gazer-${{ matrix.os }}
          path: target/dist/*